import { ExperienceCardProps } from "./ExperienceCard";

export const experiences: ExperienceCardProps[] = [
  {
    company: "Freelance / Contractor",
    location: "Remote, UK",
    role: "QA, Automation & AI Solutions Engineer",
    duration: "2026 - Present",
    details: {
      duties: [
        "Executing exploratory and functional test cycles across diverse platforms to identify and document software defects.",
        "Training Large Language Models via code-specific data annotation, logic verification, and RLHF.",
        "Generating professional diagnostic media and bug reports adhering to strict crowdtesting quality standards.",
        "Providing full-stack development and technical consultancy including, CI/CD, Test Automation, and LLM integration",
        "Building software solutions with a focus on high-fidelity frontend interfaces and robust backend logic.",
        "Performing technical requirements analysis and strategy for small businesses to ensure long-term system reliability.",
        "Implement automated data visualisation tools using D3.js and managing deployment on cloud platforms.",
      ],
      projects: [
        "Building a bespoke ERP & CMS with integrated AI to streamline processes for an established Start-up",
      ],
      skills: [
        "Exploratory Testing",
        "Session-Based Testing",
        "Functional Test Cycles",
        "Defect Root Cause Analysis",
        "Heuristic Evaluation",
        "UX & UI Quality Audits",
        "RLHF Data Annotation",
        "Logic Verification",
        "Next.js",
        "TypeScript",
        "Amazon Aurora",
        "Amazon Bedrock",
        "AWS Lambda",
        "n8n",
        "Playwright",
        "D3.js",
      ],
    },
  },
  {
    company: "S&A Academy",
    location: "Remote, UK",
    role: "Senior Technology Trainer",
    duration: "2025 - 2026",
    details: {
      duties: [
        "Designed and delivered industry-aligned curricula, including a bespoke four-week intensive bootcamp and advanced modules on OOP, SOLID principles, Debugging, Refactoring, and Design Patterns.",
        "Designed and delivered specialised training modules focused on software testing, DevOps, and automation.",
        "Designed and assessed curricula for Level 4 developers, establishing technical benchmarks and quality standards for engineering cohorts.",
        "delivered targeted coaching and code reviews to support apprentices in meeting Distinction criteria for their End-Point Assessment (EPA).",
      ],
      projects: [
        "Designed L4 Software Developer Apprenticship Programme",
        "Designed ISQTB aligned Software Testing Programme",
      ],
      skills: [
        "Object-Oriented Programming",
        "SOLID Principles",
        "Design Patterns",
        "Clean Code & Refactoring",
        "Technical Curriculum Design",
        "Pedagogical Instruction",
        "Code Review & Mentorship",
        "EPA Standards Assessment",
        "Debugging Methodologies",
        "Software Testing (QA)",
        "DevOps Foundations",
        "Automated Testing",
        "JavaScript",
        "Java",
        "Python",
        "React, Node.js, Express.js",
      ],
    },
  },
  {
    company: "Freelance / Contractor",
    location: "Remote, US",
    role: "Software Engineer and Technical Consultant",
    duration: "2024 - 2025",
    details: {
      duties: [
        "Consulted for start-ups, SMEs, and sole-proprietors to determine requirements and align technical strategy for bespoke software builds.",
        "Engineered custom internal systems and customer-facing websites as an independent contractor.",
        "Developed and deployed native applications tailored to specific client specifications.",
        "Provided technical tuition and mentorship on software engineering principles and best practices.",
      ],
      projects: [
        "Developed a life coaching platform with a personalised members portal, dynamic course hosting, and algorithmic content recommendations.",
        "Engineered a native mobile application featuring social forums and dynamic data retrieval for the US market.",
        "Developed proprietary IoT software for vintage camper monitoring, integrating physical sensors to automate safety checklists and system tracking.",
      ],
      skills: [
        "React & Next.js",
        "TypeScript & JavaScript",
        "Node.js & Express",
        "RESTful API Design",
        "PostgreSQL & MongoDB",
        "React Native",
        "Mobile UI/UX Design",
        "Graph QL",
        "AWS Lambda",
        "IoT & Sensor Integration",
        "State Management (Redux)",
        "CI/CD Pipelines",
        "Docker & Containerisation",
        "Cloud Infrastructure (AWS)",
        "Unit & Integration Testing",
        "Responsive Web Design",
      ],
    },
  },
  {
    company: "Thoughtworks",
    location: "London, UK / Denver, Colorado, US",
    role: "Consultant Software Engineer",
    duration: "2019 - 2023",
    details: {
      duties: [
        "Developed full-stack solutions for government and enterprise clients using React, TypeScript, Java/Spring, and Clojure within strictly Agile environments.",
        "Engineered cloud infrastructure and containerised microservices using AWS, Azure, GCP, Terraform, Docker, and Kubernetes.",
        "Built comprehensive test suites across the full pyramid, including Unit, Integration, Contract, and E2E, ensuring automated testing as a core Definition of Done.",
        "Developed contract tests for complex microservice architectures using Swagger and automated API suites with Postman to ensure service reliability.",
        "Served as SME for Web Accessibility, leading comprehensive overhauls of corporate and client projects to ensure equitable technology standards.",
        "Collaborated in Three Amigos sessions and paired frequently with QAs to define data strategies and quality benchmarks for complex codebases.",
        "Implemented event-driven architectures using Quarkus and Event Sourcing within high-scale enterprise environments.",
        "Mentored junior developers and steered inclusion initiatives, contributing to disability and neurodiversity policies within the engineering department.",
      ],
      projects: [
        "Collaborated with senior engineers to develop a comprehensive data strategy for a large international travel company.",
        "Built a bespoke micro-app framework for a global fuel company to enable regional app development with shared features and testing.",
        "Engineered a management and reporting product for a national education provider using React, .NET, and Terraform.",
        "Led the development of a React-based social amplification tool for internal global marketing campaigns.",
        "Delivered an event-sourced internal application for a UK Government body to track over 700 digital services.",
        "Developed event-driven microservices for a large UK financial institution to determine postgraduate loan eligibility.",
        "Created a high-fidelity Vue.js companion app for a major corporate event, featuring interactive maps and real-time agenda updates.",
        "Developed an internal training course to teach Test-Driven Development (TDD) in Java and JavaScript to junior consultants.",
      ],
      skills: [
        "Java & Spring Boot",
        "Clojure & Functional Programming",
        "Vue.js & React",
        "TypeScript",
        "TDD & Unit Testing (JUnit/Jest)",
        "Contract & API Testing",
        "Event-Driven Architecture",
        "Microservices Architecture",
        "PostgreSQL & MongoDB",
        "Event Sourcing (Quarkus)",
        "Cloud Infrastructure (AWS/Azure/GCP)",
        "Terraform & Infrastructure as Code",
        "Docker & Kubernetes",
        "CI/CD (CircleCI/GoCD)",
        "Web Accessibility (WCAG)",
      ],
    },
  },
  {
    company: "Manchester Digital",
    location: "Manchester UK",
    role: "Development Coach",
    duration: "2017 - 2019",
    details: {
      duties: [
        "Coordinated the development and launch of the Level 4 Software Developer Apprenticeship, ensuring all curricula aligned with the Government Trailblazer Standard.",
        "Managed the end-to-end recruitment and onboarding process for engineering cohorts across multiple partner organisations.",
        "Collaborated with industry experts to translate professional requirements into structured learning frameworks and technical benchmarks.",
        "Provided coaching and professional development support to apprentices, overseeing their progress against the apprenticeship framework.",
        "Ensured programme compliance and quality assurance by mapping educational delivery to national assessment criteria.",
      ],
      projects: [
        "Developed and delivered a Portfolio Masterclass to help developers document technical growth and evidence competencies for professional assessment.",
        "Designed and led intensive EPA (End-Point Assessment) preparation sessions to ensure candidates met national Distinction criteria.",
        "Coordinated the end-to-end recruitment and technical onboarding for Software Developer apprenticeship cohorts.",
        "Acted as the primary logistical lead for a large-scale apprenticeship programme, bridging the gap between employer requirements and educational standards.",
      ],
      skills: [
        "Software Development Life Cycle (SDLC)",
        "Agile & Scrum Methodologies",
        "Knowledge, Skills & Behaviours (KSB) Mapping",
        "Technical Standards & Compliance",
        "Stakeholder Management",
        "Requirement Elicitation",
        "Technical Coaching & Mentorship",
        "Strategic Resource Planning",
        "Regulatory Framework Alignment",
        "Industry Engagement & Networking",
      ],
    },
  },
  {
    company: "Catax",
    location: "Manchester UK",
    role: "IT Manager & Quality Coordinator",
    duration: "2015 - 2017",
    details: {
      duties: [
        "Managed IT operations and oversaw the project management for bespoke ERP and Salesforce CRM implementations.",
        "Established a comprehensive Quality Management System (QMS) and led the successful transition to ISO 9001:2015 accreditation.",
        "Gathered business requirements and translated them into technical specifications and detailed test cases.",
        "Developed and executed structured test plans and strategy documents for internal system updates and new feature releases.",
        "Conducted manual blackbox testing and User Acceptance Testing (UAT) for all internal system updates and new feature releases.",
        "Performed database testing and verified data integrity using SQL to ensure accurate processing and storage.",
        "Modernised IT infrastructure and helpdesk processes to strengthen data security and operational scalability.",
      ],
      projects: [
        "Led the company-wide transition and audit process to achieve ISO 9001:2015 Quality Management certification.",
        "Managed the end-to-end implementation and project lifecycle of a bespoke ERP system and Salesforce CRM integration.",
        "Developed a structured IT helpdesk and infrastructure upgrade to support high-growth business operations.",
        "Managed the project lifecycle and UAT phase for a large-scale Salesforce CRM integration and data migration.",
        "Designed and executed comprehensive UAT and manual testing cycles for a multi-phase corporate rebranding and system merger.",
      ],
      skills: [
        "Quality Management Systems (ISO 9001)",
        "Test Planning & Strategy",
        "User Acceptance Testing (UAT)",
        "Test Design (BVA, Equivalence Partitioning)",
        "Manual Blackbox Testing",
        "SQL & Database Testing",
        "Requirement Elicitation",
        "Systems Analysis",
        "Project Management (ERP/CRM)",
        "IT Governance & Compliance",
      ],
    },
  },
];
